# Generated by Django 3.1.3 on 2020-11-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datos_uma',
            fields=[
                ('id_uma', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=10)),
                ('uma', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=10, max_digits=13)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=13)),
                ('mp01', models.IntegerField()),
                ('mp25', models.IntegerField()),
                ('mp10', models.IntegerField()),
                ('d03', models.IntegerField()),
                ('d05', models.IntegerField()),
                ('d01', models.IntegerField()),
                ('d25', models.IntegerField()),
                ('d50', models.IntegerField()),
                ('d10', models.IntegerField()),
                ('vel', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
